# This workflow will build a .NET application
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish ECommerce.sln -c Release -o release — nologo
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact API
        path: /home/runner/work/ECommerce/release/
